config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'statics#landing'
	get 'landing', to: 'statics#landing'
	get 'home', to: 'statics#home'
	get 'about', to: 'statics#about'
	get 'contact', to: 'statics#contact'
	get 'thankyou', to: 'statics#thankyou'
	get 'admin_panel', to: 'statics#panel'

	get 'summit', to: 'statics#summit'
	get 'under_development', to: 'statics#under_development'
	get 'all_events', to: 'events#all_events'
	get 'all_members', to: 'members#all_members'
	get 'all_econsiders', to: 'econsiders#all_econsiders'
	get 'all_dialogues', to: 'dialogues#all_dialogues'

	get 'ameuxadminsignup', to: 'users#new'
	resources :users, except: [:new]

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	resources :events
	resources :dialogues
	resources :members
	resources :econsiders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dialogue.rb
class Dialogue < ApplicationRecord  
	mount_uploader :dialoguepic, DialoguepicUploader
end

app/models/econsider.rb
class Econsider < ApplicationRecord  
	belongs_to :user
	mount_uploader :postimg, PostimgUploader

	validates :user_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord  
	mount_uploader :eventpic, EventpicUploader
end

app/models/member.rb
class Member < ApplicationRecord  
	mount_uploader :profpic, ProfpicUploader
end

app/models/user.rb
class User < ApplicationRecord  
	has_many :econsiders
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?

	def red
		redirect_to under_development_path
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			redirect_to root_path
		end
	end

end

app/controllers/dialogues_controller.rb
class DialoguesController < ApplicationController
	before_action :set_timezone
	# before_action :red
	before_action :require_user

	def index
	end

	def all_dialogues
	end

	def new 
		@dialogue = Dialogue.new
	end

	def create
		@dialogue = Dialogue.new(dialogue_params)
		if @dialogue.save
			redirect_to new_dialogue_path
		else
			render 'new'
		end
	end

	def show
		@dialogue = Dialogue.find(params[:id])
	end

	def edit
		@dialogue = Dialogue.find(params[:id])
	end

	def update 
		@dialogue = Dialogue.find(params[:id])
		if @dialogue.update(dialogue_params)
			redirect_to all_events_path
		else
			render 'show'
		end
	end

	def destroy
		@dialogue = Dialogue.find(params[:id])
		@dialogue.destroy
		# flash[:notice] = "Article was successfully deleted"
		redirect_to all_events_path
	end

	private 
	def set_timezone
		Time.zone = "Kuala Lumpur"
	end
	def dialogue_params 
		params.require(:dialogue).permit(:title, :interviewee, :video_link, :dialoguepic)
	end
end

app/controllers/econsiders_controller.rb
class EconsidersController < ApplicationController
	before_action :set_timezone
	# before_action :red
	before_action :require_user, except: [:index, :show, :new, :create]

	def index
		@econsiders = Econsider.all.order("created_at DESC")
	end

	def new 
		@econsider = Econsider.new
	end

	def create
		@econsider = Econsider.new(econsider_params)
    @econsider.user_id = current_user.id
		if @econsider.save
			redirect_to econsider_url(@econsider)
		else
			render 'new'
		end
	end

	def show
		@econsider = Econsider.find(params[:id])
	end

	def edit
		@econsider = Econsider.find(params[:id])
	end

	def update 
		@econsider = Econsider.find(params[:id])
		if @econsider.update(econsider_params)
			redirect_to all_econsiders_path
		else
			render 'show'
		end
	end

	def destroy
		@econsider = Econsider.find(params[:id])
		@econsider.destroy
		# flash[:notice] = "Article was successfully deleted"
		redirect_to all_econsiders_path
	end

	private 
	def set_timezone
		Time.zone = "Kuala Lumpur"
	end
	def econsider_params 
		params.require(:econsider).permit(:title, :post_heading, :postimg, :author, :post)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_timezone
	# before_action :red
	before_action :require_user, except: [:index]

	def index
		@upcoming = Event.where('datetime > ?', Time.now)
		@past = Event.where('datetime < ?', Time.now)
	end

	def all
		@events = Event.all
		@dialogues = Dialogue.all
	end

	def new 
		@event = Event.new
		# redirect_to all_events_path
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to new_event_path
		else
			render 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update 
		@event = Event.find(params[:id])
		if @event.update(event_params)
			redirect_to all_events_path
		else
			render 'show'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		# flash[:notice] = "Article was successfully deleted"
		redirect_to all_events_path
	end

	private 
	def set_timezone
		Time.zone = "Kuala Lumpur"
	end
	def event_params 
		params.require(:event).permit(:title, :datetime, :venue, :link, :eventpic)
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	before_action :set_timezone
	# before_action :red
	before_action :require_user, except: [:index]

	def index
		@uk = Member.all.where("region = 'UK'")
		@my = Member.all.where("region = 'MY'")
	end

	def new 
		@member = Member.new
	end

	def create
		@member = Member.new(member_params)
		if @member.save
			redirect_to new_member_path
		else
			render 'new'
		end
	end

	def show
		@member = Member.find(params[:id])
	end

	def edit
		@member = Member.find(params[:id])
	end

	def update 
		@member = Member.find(params[:id])
		if @member.update(member_params)
			redirect_to all_members_path
		else
			render 'show'
		end
	end

	def destroy
		@member = Member.find(params[:id])
		@member.destroy
		# flash[:notice] = "Article was successfully deleted"
		redirect_to all_members_path
	end

	private 
	def set_timezone
		Time.zone = "Kuala Lumpur"
	end
	def member_params 
		params.require(:member).permit(:region, :office, :name, :designation, :facebook, :linkedin, :twitter, :ig, :email, :profpic)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			# flash[:success] = "You are logged in"
			redirect_to admin_panel_path
		else
			# flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end

	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	
	before_action :require_user, only: :panel
	# before_action :red, except: [:thankyou, :summit, :under_development, :contact]
	def home 
	end

	def about
	end

	def contact
	end

	def thankyou
	end

	def summit
	end

	def under_development 
	end

	def landing 
	end

	def panel
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, except: [:new, :create]

	def new
		@user = User.new
	end

	def index
		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save 
			flash[:success] = "Welcome"
			redirect_to all_econsiders_path
		else
			render 'new'
		end
	end

	private 
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dialogues/all_dialogues.html.erb
<style type="text/css">
    footer {
        margin-top: 100px;
    }
</style>

<br><br><br>
<div class="container table-container">
    <div class="row">
        <div class="col-md-5 col-12">
            <h1 class="demi">Dialogue Settings</h1>
            <hr>
            
            <%= link_to '<i class="fas fa-comments" ></i> Create New Dialogue'.html_safe, new_dialogue_path, class: "btn btn-success mb-4" %>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table id="dialogues-table" class="display">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Interviewee</th>
                        <th>Action</th>
                    </tr>
                </thead>
            <% Dialogue.all.each do | dialogue | %>
            <tbody>
                <tr>
                    <td><%= dialogue.title %></td>
                    <td><%= dialogue.interviewee %></td>
                    <td><%= link_to 'Edit', edit_dialogue_path(dialogue), class: 'btn btn-warning' %>
                        <%= link_to 'Delete', dialogue_path(dialogue), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
                </tr>
            </tbody>
            <% end %>
            </table>
        </div>
    </div>
</div>

app/views/dialogues/edit.html.erb
<style type="text/css">
    label {
        font-family: "Medium";
    }
    footer {
        margin-top: 80px;
    }
</style>

<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-5 col-12">
            <h1 class="demi">Edit Dialogue</h1>
            <hr>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-md-5 col-12 py-4">
        <%= form_for @dialogue do |f| %>

        <label>Title</label>
        <%= f.text_field :title, class: "col form-control" %>

        <label>Image <span class="text-danger">(Must be 2:1 W x H)</span></label>
        <%= f.file_field :dialoguepic, class: "col form-control" %>

        <label>Interviewee</label>
        <%= f.text_field :interviewee, class: "col form-control" %>

        <label>Video Link</label>
        <%= f.text_field :video_link, class: "col form-control" %>

        <%= f.submit class: "btn btn-success" %>
        <%= link_to "Back", all_dialogues_path, :class => "my-3 btn btn-outline-primary" %>

        <% end %>
        </div>
    </div>
</div>

app/views/dialogues/new.html.erb
<style type="text/css">
    label {
        font-family: "Medium";
    }
    footer {
        margin-top: 100px;
    }
</style>

<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-5 col-12">
            <h1 class="demi">Create New Dialogue</h1>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-12 py-4">
        <%= form_for @dialogue do |f| %>

        <label>Title</label>
        <%= f.text_field :title, class: "col form-control" %>

        <label>Image <span class="text-danger">(Must be 2:1 W x H)</span></label>
        <%= f.file_field :dialoguepic, class: "col form-control" %>

        <label>Interviewee</label>
        <%= f.text_field :interviewee, class: "col form-control" %>

        <label>Video Link</label>
        <%= f.text_field :video_link, class: "col form-control" %>

        <%= f.submit class: "btn btn-success" %>
        <%= link_to "Back", all_dialogues_path, :class => "my-3 btn btn-outline-primary" %>

        <% end %>
        </div>
    </div>
</div>

app/views/econsiders/all_econsiders.html.erb
<style type="text/css">
    footer {
        margin-top: 100px;
    }
</style>

<br><br><br>
<div class="container table-container">
    <div class="row">
        <div class="col-md-5 col-12">
            <h1 class="demi">Econsiders Table</h1>
            <hr>
            <%= link_to '<i class="far fa-newspaper" ></i> Create New E-Consider'.html_safe, new_econsider_path, class: "btn btn-success mb-4" %>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table id="econsiders-table" class="display">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Posted On</th>
                        <th>Action</th>
                    </tr>
                </thead>
            <% Econsider.all.each do |econsider| %>
            <tbody>
                <tr>
                    <td><%= econsider.title %></td>
                    <td><%= econsider.author %></td>
                    <td><%= econsider.created_at.strftime("%B %d, %Y") %></td>
                    <td><%= link_to 'Edit', edit_econsider_path(econsider), class: 'btn btn-warning' %>
                        <%= link_to 'Delete', econsider_path(econsider), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
                </tr>
            </tbody>
            <% end %>
            </table>
        </div>
    </div>
</div>

app/views/econsiders/index.html.erb
<!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item text-center">
                            <h2>AMEU Research</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<!-- breadcrumb start-->

<!-- Main Content -->
<div class="container py-4 my-4">
  <div class="row pb-4">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @econsiders.each do |econsider| %>
      <div class="post-preview">
          <%= link_to econsider_path(econsider) do %>
            <h2 class="post-title"><%= econsider.title %></h2>
            <h3 class="post-subtitle"><%= econsider.post_heading %></h3>
          <% end %>
        <p class="post-meta">Posted by <%= econsider.author %> on <%= econsider.created_at.strftime("%B %d, %Y") %></p>
      </div>
      <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/events/all_events.html.erb
<style type="text/css">
    footer {
        margin-top: 100px;
    }
</style>

<br><br><br>
<div class="container table-container">
    <div class="row">
        <div class="col-md-5 col-12">
            <h1 class="demi">Events Table</h1>
            <hr>
            <%= link_to '<i class="fas fa-calendar-day" ></i> Create New Event'.html_safe, new_event_path, class: "btn btn-success mb-4" %>
            
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table id="events-table" class="display">
                <thead>
                    <tr>
                        <th>Event Title</th>
                        <th>Date Time</th>
                        <th>Venue</th>
                        <th>Action</th>
                    </tr>
                </thead>
            <% Event.all.each do | event | %>
            <tbody>
                <tr>
                    <td><%= event.title %></td>
                    <% if event.datetime.to_time != nil %>
                    <td><%= event.datetime.to_time.strftime("%d %b %Y, %I:%M %p") %></td>
                    <% end %>
                    <td><%= event.venue %></td>
                    <td><%= link_to 'Edit', edit_event_path(event), class: 'btn btn-warning' %>
                        <%= link_to 'Delete', event_path(event), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
                </tr>
            </tbody>
            <% end %>
            </table>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<style type="text/css">
    a {
        text-decoration: none !important;
    }

    ul li a {
        color: white;
    }
    #footer {
        background-color: #111;
        color: white;
    /*    height: 200px;*/
        padding: 60px 0;
        font-family: "Light";
    }
    #footer hr {
        background-color: white;
    }

    .foot-notes {
        font-size: 14px;
    }

    .social-holder {
        display: block;
        width: auto;
    }

    .socials {
        display: inline-block;
    /*    padding: 20px;*/
        width: 50px;
        height: 50px;
        text-align: center;
        padding: 12px;
        border-radius: 50%;
        font-size: 20px;
        margin: 0 10px 0 0;
        transition: 0.2s;
        background-color: white;
        color: black;
    }

    .socials:hover {
    /*    background-color: black;*/
        color: white;
        transform: scale(1.15);
    }

    .facebook {
        color: #3b5998;
    }

    .facebook:hover {
        background-color: #3b5998;
    }

    .instagram {
        color: #FD1D1D;
    }

    .instagram:hover {
        background-color: #FD1D1D;
    }

    .linkedin {
        color: #0077B5;
    }

    .linkedin:hover {
        background-color: #0077B5;
    }

    .credits {
        text-align: right;
        padding-top: 0px;
    }

    .credits p {
        margin-bottom: 0;
        font-size: 16px;
    }

    #footer hr {
        background-color: white;
        opacity: 0.3;
        margin: 10px 0;
    }

    #footer ul {
        list-style: none;
        padding: 0px;
    }

    #footer ul li {
        font-family: "Light";
        font-size: 16px;
        line-height: 2;
    }

    #footer .sub-heading {
        padding-top: 20px;
    }
</style>
<footer class="container-fluid" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md">
                <p class="sub-heading dodgerblue medium">Follow Us</p>
                <div class="my-3">
                    <a href="https://www.facebook.com/ameunetwork/" target="_blank">
                        <div class="socials facebook">
                            <i class="fab fa-facebook-f"></i>
                        </div>
                    </a>
                    <a href="https://www.instagram.com/ameunetwork/" target="_blank">
                        <div class="socials instagram">
                            <i class="fab fa-instagram"></i>
                        </div>
                    </a>
                    <a href="https://www.linkedin.com/company/ameu/" target="_blank">
                        <div class="socials linkedin">
                            <i class="fab fa-linkedin-in"></i>
                        </div>
                    </a>
                </div>  
            </div>

            <div class="col-md col-6">
                <p class="sub-heading dodgerblue medium">Know More</p>
                <ul>
                    <li><%= link_to "Who We Are", about_path %></li>
                    <li><%= link_to "Events", events_path %></li>
                    <li><%= link_to "Our Members", members_path %></li>
                    <li>Student Guides</li>
                    <li><%= link_to "AMEU Research", econsiders_path %></li>
                </ul>
            </div>

            <div class="col-md col-6">
                <p class="sub-heading dodgerblue medium">Get In Touch</p>
                <ul>
                    <li>Apply to join</li>
                    <li><%= link_to "Contact Us", contact_path %></li>
                </ul>
            </div>

        </div>
        <hr class="my-4">
        <p class="text-white lead foot-notes">Copyright &copy; <span id="year"></span> AMEU. <span class="float-right">All Rights Reserved.</span></p>
    </div>
</footer>

<script>
  var d = new Date();
  var n = d.getFullYear();
  document.getElementById("year").innerHTML = n;
</script>

app/views/layouts/_navigation.html.erb
<header id="navbar-old">
    <nav class="navbar navbar-expand-md fixed-top">
        <div class="container">
        <!-- Brand -->
            <div id="logo">
                <%#= image_tag("home/ameu-globe.png", width: "40px", class: "align-top", id: "logo-img")%>
                <img src="https://lh4.googleusercontent.com/MMRdjAJtoocInFd7jFrcJ7XPRV3l9qTqF1AJfXVlV53EkL_OBF_rf6AhrWnzatL2HZb-5UqySPDoO9v0Wnet0VWj5Th6C8pbNsbM3jduOiOc8w-xuirLRwSe-ey04AH7Q4J1YdXa" width="130px" class="align-top" id="logo-img">
                <%#= link_to "AMEU", root_path, :class => 'nav-link navbar-brand align-center' %>
            </div>

            <!-- Toggler/collapsibe Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" style="padding: 0">
            <span class="navbar-toggler-icon"><%= image_tag("menu-ham.png", width: "100%" )%></span>
            </button>

            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <%= link_to "About", about_path, :class => 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Events", events_path, :class => 'nav-link' %>
                    </li> 
                    <li class="nav-item">
                        <%= link_to "Leadership", members_path, :class => 'nav-link' %>
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link">Student Guides</a>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Research", econsiders_path, :class => 'nav-link' %>
                    </li>
                    <li class="nav-item" id="contact-btn-holder">
                        <%= link_to "Contact", contact_path, :class => 'nav-link', id: "contact-btn" %>
                    </li> 
                </ul>
            </div> 
        </div>
    </nav>
</header>

app/views/layouts/_new_nav.html.erb
<header class="main_menu home_menu">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand"> <img src="https://lh4.googleusercontent.com/MMRdjAJtoocInFd7jFrcJ7XPRV3l9qTqF1AJfXVlV53EkL_OBF_rf6AhrWnzatL2HZb-5UqySPDoO9v0Wnet0VWj5Th6C8pbNsbM3jduOiOc8w-xuirLRwSe-ey04AH7Q4J1YdXa" alt="logo" width="150px"> </a>
                    
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="" >
                        <span class="ti-menu"></span>
                    </button>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="border-color: rgb(120,120,120); border-radius:2px; padding: 4px 8px">
                        <%= image_tag("menu-ham.png", width: '28px') %>
                    </button>

                    <div class="collapse navbar-collapse main-menu-item justify-content-end"
                        id="navbarSupportedContent">
                        <ul class="navbar-nav align-items-center">
                            <li class="nav-item">
                                <%= link_to "Home", landing_path, :class => 'nav-link' %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "About", about_path, :class => 'nav-link' %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Events", events_path, :class => 'nav-link' %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Leadership", members_path, :class => 'nav-link' %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Research", econsiders_path, :class => 'nav-link' %>
                            </li>

                            <!-- <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Pages
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="Event.html">Event</a>
                                    <a class="dropdown-item" href="elements.html">Elements</a>
                                </div>
                            </li> -->

                            <li class="nav-item">
                                <%= link_to "Contact", contact_path, :class => 'nav-link', id: "contact-btn" %>
                            </li>

                            <% if logged_in? %>
                            <li class="nav-item dropdown col">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-cog"></i> Admin</a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <%= link_to "Admin Panel", admin_panel_path, :class => 'dropdown-item' %>
                                    <%= link_to "Logout", logout_path, method: :delete, :class => 'dropdown-item' %>
                                </div>
                            </li>
                            <% end %>
<!--
                            <li class="d-none d-lg-block">
                                <a class="btn_3 p-2" href="#">join us</a>
                            </li>
-->
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

app/views/layouts/_research.html.erb
<!--::blog_part start::-->
    <section class="blog_part padding_bottom">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 col-md-8">
                    <div class="section_tittle text-center">
                        <h2>AMEU Research</h2>
                        <p>The only Malaysian student organization with our own independent research arm, publishing original research articles “EConsiders” and weekly news updates “EconBites”.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <% Econsider.all.order("id desc").limit(3).each do |econ| %>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_blog">
                        <div class="appartment_img">
                            <%= image_tag econ.postimg.url %>
                        </div>
                        <div class="single_appartment_content">
                            <h4><%= econ.title %></h4>
                            <p class="lead"><%= econ.post_heading %></p>
                            <p class="e-author">By <%= econ.author %></p>
                            <%= link_to 'Read More', econsider_path(econ), class: 'btn_2 py-2' %>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </section>
<!--::blog_part end::-->

app/views/members/all_members.html.erb
<style type="text/css">
    footer {
        margin-top: 100px;
    }
</style>

<br><br><br>
<div class="container table-container">
    <div class="row">
        <div class="col-md-5 col-12">
            <h1 class="demi">Members Table</h1>
            <hr>
            <%= link_to '<i class="fas fa-users" ></i> Create New Member'.html_safe, new_member_path, class: "btn btn-success mb-4" %>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table id="members-table" class="display">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Region</th>
                        <th>Office</th>
                        <th>Action</th>
                    </tr>
                </thead>
            <% Member.all.each do |member| %>
            <tbody>
                <tr>
                    <td><%= member.name %></td>
                    <td><%= member.region %></td>
                    <td><%= member.office %></td>
                    <td><%= link_to 'Edit', edit_member_path(member), class: 'btn btn-warning' %>
                        <%= link_to 'Delete', member_path(member), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
                </tr>
            </tbody>
            <% end %>
            </table>
        </div>
    </div>
</div>

app/views/statics/thankyou.html.erb
<section>
    <div class="container">
        <div class="jumbotron bg-white mt-4 white-jumbo">
            <h1 class="general-heading mt-2 mb-0 dodgerblue">Thank you!</h1>
            <h2 class="mt-2 text-center">We appreciate your interest.</h2>
        </div>
    </div>
    
</section>

app/views/statics/under_development.html.erb
<%= render 'layouts/coming_soon' %>

app/views/users/index.html.erb
<style type="text/css">
    footer {
        margin-top: 100px;
    }
</style>

<br><br><br>
<div class="container table-container">
    <div class="row">
        <div class="col-md-5 col-12">
            <h1 class="demi">Users Table</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table id="econsiders-table" class="display">
                <thead>
                    <tr>
                        <th>ID</th>                      
                        <th>Username</th>
                        <th>Action</th>
                    </tr>
                </thead>
            <% User.all.each do |user| %>
            <tbody>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= user.username %></td>
                    <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning' %>
                        <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger disabled' %></td>
                </tr>
            </tbody>
            <% end %>
            </table>
        </div>
    </div>
</div>